---
title: "Tugas 3"
author: "Harya Anggitama"
date: "9/30/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import Data 

```{r}
library(dslabs)
data(murders)
```

# Nomor 1

```{r}
pop <- murders$population
pop <- sort(pop)
pop[1]
```

# Nomor 2

```{r}
index <- order(pop)
index[1]
```

# Nomor 3

```{r}
which.min(murders$population)
```

# Nomor 4

```{r}
index <- which.min(murders$population)
negara <- murders$state
negara[index]
```

# Nomor 5

```{r}
ranks <- rank(murders$population)
my_dff <- data.frame(states = negara, ranks = ranks)
my_dff
```


# Nomor 6

```{r}
idxPop <- order(murders$population)
my_df <- data.frame(states = negara[idxPop], ranks = ranks[idxPop])
my_df
```

# Nomor 7

```{r}
population_in_millions <- murders$population / 10 ^ 6
total_gun_murder <- murders$total

log10_population <- log10(murders$population)

log10_total_gun_murders <- log10(total_gun_murder)

plot(log10_population, log10_total_gun_murders)
```

# Nomor 8

```{r}
hist(population_in_millions)
```

# Nomor 9

```{r}
boxplot(murders$population~murders$region)
```